name: Quality Control

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install 3.13
      - name: Install dependencies
        run: uv sync --frozen
      - name: Test with pytest
        run: uv run pytest tests/ --nbmake notebooks/
